export const MOODS = {
    OVERJOYED: {
      id: "overjoyed",
      label: "Overjoyed",
      emoji: "🤗",
      score: 10,
      color: "yellow",
      prompt: "What wonderful things happened today?",
      unsplashQuery: "joyful+celebration+happy",
    },
    ACCOMPLISHED: {
      id: "accomplished",
      label: "Accomplished",
      emoji: "⭐",
      score: 9,
      color: "amber",
      prompt: "What have you achieved?",
      unsplashQuery: "achievement+success+star",
    },
    INSPIRED: {
      id: "inspired",
      label: "Inspired",
      emoji: "💫",
      score: 9,
      color: "violet",
      prompt: "What's sparking your creativity?",
      unsplashQuery: "inspiration+creative+light",
    },
    PROUD: {
      id: "proud",
      label: "Proud",
      emoji: "🦁",
      score: 9,
      color: "amber",
      prompt: "What achievement are you proud of?",
      unsplashQuery: "achievement+success+proud",
    },
    LOVED: {
      id: "loved",
      label: "Loved",
      emoji: "🥰",
      score: 9,
      color: "pink",
      prompt: "Who or what is making you feel loved?",
      unsplashQuery: "love+heart+affection",
    },
    APPRECIATED: {
      id: "appreciated",
      label: "Appreciated",
      emoji: "💝",
      score: 8,
      color: "rose",
      prompt: "Who showed you appreciation?",
      unsplashQuery: "appreciation+gratitude+heart",
    },
    MOTIVATED: {
      id: "motivated",
      label: "Motivated",
      emoji: "🎯",
      score: 8,
      color: "emerald",
      prompt: "What's driving you forward?",
      unsplashQuery: "motivation+target+goal",
    },
    HAPPY: {
      id: "happy",
      label: "Happy",
      emoji: "😊",
      score: 8,
      color: "amber",
      prompt: "What's making you smile today?",
      unsplashQuery: "happy+smile+sunshine",
    },
    EXCITED: {
      id: "excited",
      label: "Excited",
      emoji: "🎉",
      score: 8,
      color: "orange",
      prompt: "What are you looking forward to?",
      unsplashQuery: "excited+energetic+celebration",
    },
    CONFIDENT: {
      id: "confident",
      label: "Confident",
      emoji: "💪",
      score: 8,
      color: "emerald",
      prompt: "What's boosting your confidence?",
      unsplashQuery: "confident+strong+power",
    },
    GRATEFUL: {
      id: "grateful",
      label: "Grateful",
      emoji: "🙏",
      score: 8,
      color: "green",
      prompt: "What are you thankful for today?",
      unsplashQuery: "grateful+thankful+blessing",
    },
    CONNECTED: {
      id: "connected",
      label: "Connected",
      emoji: "🤝",
      score: 8,
      color: "indigo",
      prompt: "Who made you feel connected today?",
      unsplashQuery: "connection+together+community",
    },
    PEACEFUL: {
      id: "peaceful",
      label: "Peaceful",
      emoji: "😌",
      score: 7,
      color: "blue",
      prompt: "What's bringing you peace?",
      unsplashQuery: "peaceful+calm+serene",
    },
    HOPEFUL: {
      id: "hopeful",
      label: "Hopeful",
      emoji: "🌱",
      score: 7,
      color: "green",
      prompt: "What gives you hope?",
      unsplashQuery: "hope+growth+spring",
    },
    CREATIVE: {
      id: "creative",
      label: "Creative",
      emoji: "🎨",
      score: 7,
      color: "violet",
      prompt: "What's inspiring your creativity?",
      unsplashQuery: "creative+art+inspiration",
    },
    THOUGHTFUL: {
      id: "thoughtful",
      label: "Thoughtful",
      emoji: "🤔",
      score: 6,
      color: "slate",
      prompt: "What's on your mind?",
      unsplashQuery: "thinking+contemplation+reflection",
    },
    CURIOUS: {
      id: "curious",
      label: "Curious",
      emoji: "🧐",
      score: 6,
      color: "teal",
      prompt: "What's caught your interest?",
      unsplashQuery: "curious+discovery+explore",
    },
    NOSTALGIC: {
      id: "nostalgic",
      label: "Nostalgic",
      emoji: "🌅",
      score: 5,
      color: "fuchsia",
      prompt: "What memories are you thinking about?",
      unsplashQuery: "nostalgia+memories+sunset",
    },
    NEUTRAL: {
      id: "neutral",
      label: "Neutral",
      emoji: "😐",
      score: 5,
      color: "gray",
      prompt: "How has your day been?",
      unsplashQuery: "neutral+balance+calm",
    },
    RESTLESS: {
      id: "restless",
      label: "Restless",
      emoji: "🌊",
      score: 4,
      color: "blue",
      prompt: "What's making you feel unsettled?",
      unsplashQuery: "restless+waves+motion",
    },
    TIRED: {
      id: "tired",
      label: "Tired",
      emoji: "😴",
      score: 4,
      color: "purple",
      prompt: "What's draining your energy?",
      unsplashQuery: "tired+sleep+rest",
    },
    OVERWHELMED: {
      id: "overwhelmed",
      label: "Overwhelmed",
      emoji: "😵",
      score: 3,
      color: "sky",
      prompt: "What's feeling like too much?",
      unsplashQuery: "overwhelmed+chaos+storm",
    },
    ANXIOUS: {
      id: "anxious",
      label: "Anxious",
      emoji: "😰",
      score: 3,
      color: "indigo",
      prompt: "What's causing your anxiety?",
      unsplashQuery: "worry+stress+anxiety",
    },
    DISAPPOINTED: {
      id: "disappointed",
      label: "Disappointed",
      emoji: "😞",
      score: 3,
      color: "stone",
      prompt: "What didn't go as expected?",
      unsplashQuery: "disappointment+rain+grey",
    },
    FRUSTRATED: {
      id: "frustrated",
      label: "Frustrated",
      emoji: "😤",
      score: 3,
      color: "orange",
      prompt: "What's blocking your progress?",
      unsplashQuery: "frustrated+blocked+obstacle",
    },
    STRESSED: {
      id: "stressed",
      label: "Stressed",
      emoji: "😫",
      score: 3,
      color: "rose",
      prompt: "What's pressuring you?",
      unsplashQuery: "stress+pressure+overwhelmed",
    },
    INSECURE: {
      id: "insecure",
      label: "Insecure",
      emoji: "🥺",
      score: 2,
      color: "lime",
      prompt: "What's making you doubt yourself?",
      unsplashQuery: "insecure+doubt+shadow",
    },
    SAD: {
      id: "sad",
      label: "Sad",
      emoji: "😢",
      score: 2,
      color: "cyan",
      prompt: "What's bringing you down?",
      unsplashQuery: "sad+melancholy+rain",
    },
    LONELY: {
      id: "lonely",
      label: "Lonely",
      emoji: "🌙",
      score: 2,
      color: "zinc",
      prompt: "How could you connect with others?",
      unsplashQuery: "lonely+solitude+night",
    },
    ANGRY: {
      id: "angry",
      label: "Angry",
      emoji: "😠",
      score: 1,
      color: "red",
      prompt: "What's frustrating you?",
      unsplashQuery: "angry+storm+thunder",
    },
  };
  
  export const getMoodTrend = (averageScore) => {
    if (averageScore >= 8) return "You've been feeling great!";
    if (averageScore >= 6) return "You've been doing well overall.";
    if (averageScore >= 4) return "You've been feeling okay.";
    if (averageScore >= 2) return "Things have been challenging.";
    return "You've been having a tough time.";
  };
  
  export const getMoodById = (moodId) => {
    return MOODS[moodId?.toUpperCase()];
  };